# -*- coding: utf-8 -*-
"""IntroducaoAnalisedeDados

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ru1TfDQHf3XbVRqmlID3kDOO1d8zHMF2

# **Bibliotecas**
"""

import pandas as pd # Trabalha com analise de dados

"""# **Passo 1 - Trazer sua base de dados para o python e analisá-la**"""

tabela = pd.read_excel('/content/drive/MyDrive/Vendas.xlsx') # Ler base de dados
display(tabela)

"""# **Passo 2 - Ter um panorama geral sobre a sua base de dados**"""

faturamento_total = tabela['Valor Final'].sum() # Seleciona a coluna e soma todos os valores
print(faturamento_total)

"""# **Passo 3 - Começar sua análise Top -> Down**"""

# Calcular Faturamento por loja
# Quando é varias colunas [[]]
faturamento_por_loja = tabela[['ID Loja', 'Valor Final']].groupby('ID Loja').sum() # Agrupa os ID's repetidos e somar seus valores
display(faturamento_por_loja)

"""# **Passo 4 - Entrar no detalhe pra entender**"""

faturamento_por_produto = tabela[['ID Loja', 'Produto', 'Valor Final']].groupby(['ID Loja', 'Produto']).sum()
display(faturamento_por_produto)